version: 2
updates:
- package-ecosystem: nuget
  directory: "/AirTNG.Web.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Twilio
    versions:
    - 5.55.0
    - 5.58.0
    - 5.59.0
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Identity.UI
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Tools
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
  - dependency-name: Moq
    versions:
    - 4.16.0
- package-ecosystem: nuget
  directory: "/AirTNG.Web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Twilio
    versions:
    - 5.54.0
    - 5.55.0
    - 5.56.0
    - 5.57.0
    - 5.58.0
  - dependency-name: Microsoft.EntityFrameworkCore.Tools
    versions:
    - 5.0.2
    - 5.0.5
  - dependency-name: Microsoft.AspNetCore.Identity.UI
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.2
